version: "2"
services:
  web:
    container_name: taleit-web
    build: ./web
    env_file: .env
    environment:
      - NODE_ENV=development
    volumes:
      - ./web:/app/:rw
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
