#!/bin/bash

# Get current directory
current_dir=$(cd -P "$(dirname "$0")" && pwd)

# Start docker-machine
docker-machine start taleit

# Set environment
source "$current_dir/scripts/set-environment.sh"

# SSH forwarding
docker-machine ssh taleit -f -N -L "$WEB_PORT:localhost:$WEB_PORT"

# Run docker-compose
docker-compose up -d

# Open logs
docker-compose logs
