#!/usr/bin/env node

const program = require('commander');

program
  .version('0.0.1')
  .command('start', 'Start development environment', { isDefault: true })
  .command('stop', 'Stop development environment and tear down all resources used')
  .parse(process.argv);
