#!/bin/bash

DOCKER_MACHINE=taleit
docker-machine create --driver virtualbox $DOCKER_MACHINE

# Source default docker-machine
docker-machine start $DOCKER_MACHINE
eval $(docker-machine env $DOCKER_MACHINE)

# TODO: Load .env

# SSH forwarding
docker-machine ssh $DOCKER_MACHINE -f -N -L "3000:localhost:3000"

# Run docker-compose
docker-compose up -d

docker-compose logs
